yarkinsiyez35/308-Repository-Backend-FlightScheduler

FlightScheduler/pom.xml
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotLanguageEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/main/resources/application.properties

Added folder structure. Created entity classes for pilot. Created Service Repository and Controller classes for Pilot.

Starting Point

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotLanguageEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotLanguagePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Model/PilotWithLanguages.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotLanguageRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/main/resources/application.properties

Added mapping between PilotEntity and PilotLanguageEntity. Changed the functionality of PilotService.

Added mapping

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/LoginDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/LoginRequest.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotSimplifiedDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotWithLanguagesDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/main/resources/application.properties

Added some DTO's that will be needed in future requirements. Added authenticate ability to pilot service and controller.

New functionality for Pilot Controller

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AdminEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AirportEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CompanyEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/FlightEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PlaneEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/VehicleTypeEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/AdminRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/AirportRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CompanyRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/FlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PlaneRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/VehicleTypeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

Only Crude Operations is done for now. Might need to update.

Flight API

---

.idea/.gitignore
.idea/308-Repository.iml
.idea/compiler.xml
.idea/encodings.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AttendantLanguageEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AttendantLanguagePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntity.java

Added Cabin crew entities

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotWithLanguagesDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java

Pilot Controller now fully supports Creating, Reading and Deleting a Pilot Entity.

Added CRD to PilotAPI

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotLanguageRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/main/resources/application.properties

PilotController is fully functional, added additional comments to the PilotController and PilotServiceImp for  better readability

added Update to PilotAPI

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotAssignmentEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotAssignmentPK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotAssignmentRepository.java

created the representation for pilot_languages table and added mapping for PilotEntity. However, not tested with dummy values.

created PilotAssignmentEntity

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java

Pilot services can now throw exceptions and Pilot Controller code has been modified to catch those thrown exceptions and respond accordingly.

Added try catch block to pilot controller

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java

Added @Transactional annotation for the Services of 4 APIs.

Added @Transactional annotation for Services

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/CabinCrewFullDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AttendantVehicleTypeEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AttendantVehicleTypePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewAssignmentsEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewAssignmentsPK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntity.java

Implemented Cabin Crew DTO with all details, also implemented entity mapping for cabin crew

Cabin Crew DTO with all details

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotLanguageEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PilotLanguageRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PilotRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/PilotServiceTests.java

Added PilotService tests and fixed a problem in PilotRepository tests. Removed reduntant tests in repositories.

Added Service testing for Pilot

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PassengerEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Controller/AuthenticationController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/DTO/RegistrationDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/AuthenticationService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerServiceImp.java
FlightScheduler/src/main/resources/application.properties
db_population.sql
db_script.sql

Now a user can register as a passenger. Also fixed some errors in sql statements.

Added Registration capability

---

FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/PilotServiceTests.java

Completed tests for PilotService.

Completed Tests For Pilot Service

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotAssignmentDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotFullDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotSimplifiedDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotWithLanguagesDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java

This DTO has every information about a pilot. This DTO will be returned in few of the endpoints in Pilot API.

Added PilotFullDTO

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinCrewRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinLanguageRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinRecipeRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/CabinCrewServiceTests.java

Tests For CabinCrewRepositoryTests, CabinLanguageRepositoryTests, CabinRecipeRepositoryTests and CabinCrewServiceTests.

Tests For CabinCrew Services and Repos

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/FlightInfoForPilotDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotAssignmentDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotWithLanguagesAsStringDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/PilotDTOs/PilotWithLanguagesDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentService.java
FlightScheduler/src/main/resources/application.properties

Added PilotWithLanguagesAsStringDTO, this DTO will be used to communicate between front end communication for creating updating and deleting Pilot in PilotAPI.

Added PilotWithLanguagesAsStringDTO

---

.idea/.gitignore
.idea/308-Repository.iml
.idea/compiler.xml
.idea/misc.xml
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/FlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/VehicleTypeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/resources/application.properties

This update;
- closes #53 
- closes #54 
- closes #55 
, and makes minor improvement on the Flight API

Flight branch update 1

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/CabinCrewAPI/CabinCrewController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/CabinCrewDTOs/AttendantWithLanguagesAsStringDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/CabinCrewDTOs/AttendantWithLanguagesDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/CabinCrewDTOs/CabinCrewFullDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/AttendantLanguageEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/AttendantLanguagePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/AttendantVehicleTypeEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/AttendantVehicleTypePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/CabinCrewAssignmentsEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/CabinCrewAssignmentsPK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/CabinCrewEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/DishRecipeEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/DishRecipePK.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinAssignmentRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinCrewRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinLanguageRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinVehicleTypeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/DishRecipeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Model/ApplicationUser.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/UserService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantServiceImp.java
FlightScheduler/src/main/resources/application.properties
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinCrewRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinLanguageRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinRecipeRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/CabinCrewServiceTests.java

DTOs updated and services are updated too

cabin crew DTOs updated

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/FlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

This branch;
- closes #71 
- closes #72 
- closes #73 
- closes #74 
, and does some minor improvements in the codebase of the Flight API

Updates and modifications cover the tasks #71, #72, #73, and #74.

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotFlightAssignmentController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java
FlightScheduler/src/main/resources/application.properties

Now every pilot of the given flight can be returned with their role and seats in the requested DTO format.

Added functionality to FlightAssignment Service

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotFlightAssignmentController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/CabinCrewEntites/CabinCrewAssignmentsEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotAssignmentEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinAssignmentRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/SeatIncrementer.java

A pilot can now be assigned to a flight. Also SeatIncrementer is created to assign seat numbers for pilot and cabin crew.

Added capability to assing a Pilot to a flight

---

.idea/uiDesigner.xml
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/SeatDTOs/SeatingDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/SeatDTOs/SeatingTypeDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/SeatDTOs/Seats.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PassengerFlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/VehicleTypeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

This update;
- closes #79 
- closes #80 
- closes #81 
- closes #82
, and does some minor improvements/modifications on the codebase.

Updates and modifications cover the tasks #79, #80, #81, and #82.

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepositories/PilotAssignmentRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepositories/PilotRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/FlightDateChecker.java

Added necessary components for finding the available pilots for a given flight. Functionality is not finished yet.

Added needed components for finding available pilots

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotFlightAssignmentController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/FlightDateChecker.java

PilotFlightAssignment can now show available pilots that are eligible to be assigned to a particular flight.

PilotFlightAssignmentService can now return available pilots

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java

Bug fix in UserDataDTOFactory

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/FlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java

Now the format is completely the same expected from front end

Added SeatingDTO to UserFlightDataDTO

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/PilotEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/AuthenticationService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java
db_script.sql

Added email control to pilot service and also added option to create a pilot with giving id.

Added email control and option to create a pilot without id

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/FlightDataDTO.java

Added Menu to FlightDataDTO

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/AdminRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Model/ApplicationUser.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/AuthenticationService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/UserService.java

ApplicationUser now also holds id of the user. Also, login for admin is implemented as well.

Added id attribute to ApplicationUser

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinCrewRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantAssignmentServiceImp.java
FlightScheduler/src/main/resources/application.properties

Minor bug fix in CabinCrewAssignment repository and service. It is working now.

Minor bug fix in CabinCrewAssignment repository and service

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/FlightEntity.java

Added mapping of FlightEntity to  CabinCrewAssignmentEntity and PilotAssignmentEntity. This mapping allows Flight Entity to be deleted without violating constraints.

Added mapping to FlightEntity

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/SeatTypeFinder.java

Added Utility class to find the seat type of a passenger. Code is taken from FlightServiceImp.

Added Utility class to find the seat type of a passenger

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Configuration/SecurityConfiguration.java

Created MainSystemController. This controller will be the main interaction point with the front end. Authorizations are also updated accordingly to the rules.

Created MainSystemController

---

db_population.sql
db_script.sql

added end_to_end_distance table and its dummy data to sql script

added table to sql script

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PassengerAPI/PassengerController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Configuration/SecurityConfiguration.java

Added UserDataDTO conversion from Passenger Entity. Also, modified PassengerController.

Modified PassengerAPI

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/CabinCrewAPI/CabinCrewController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Configuration/SecurityConfiguration.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Model/ApplicationUser.java

CrossOrigin allows access from front end.

Added CrossOrigin to connect front end with backend

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/CabinCrewAPI/CabinCrewController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/FlightAPI/FlightController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PassengerAPI/PassengerController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/PilotAPI/PilotController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/AdminRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/AirportRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinAssignmentRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinCrewRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinLanguageRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/CabinVehicleTypeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/CabinCrewRepositories/DishRecipeRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/FlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PassengerFlightRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PassengerRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepositories/PilotAssignmentRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepositories/PilotLanguageRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Repository/PilotRepositories/PilotRepository.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Controller/AuthenticationController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/AuthenticationService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/UserService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantAssignmentServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerFlightServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotFlightAssignmentServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PilotServiceImp.java

Added comments on classes that need testing.

Wrote what should be tested

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AdminEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Controller/AuthenticationController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Service/AuthenticationService.java

Now a user can reset their password.

Added forgetPassword option

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/AdminEntity.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/AdminRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinCrewLanguageRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/CabinVehicleTypeRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/DishRecipeRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PassengerFlightRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PilotLanguagesRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PilotRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/PilotFlightAssignmentServiceTests.java

test classes added for missing repositories and services

test classes added

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/AttendantAssignmentServiceImp.java
FlightScheduler/src/main/resources/application.properties

Controller functions for Passenger will be filled today.

Added controller functions for Passenger

---

FlightScheduler/src/main/resources/application.properties
db_population.sql

Decreased number of cabin crew for each plane.

Modified db_population

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Entity/FlightEntitites/CityEntity.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Security/Configuration/SecurityConfiguration.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/SeatTypeFinder.java

Adding @Table annotation fixed it.

Fixed bug in CityEntity

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

Updates and modifications cover the task #135

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

Updates and modifications cover the task #136

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Util/SeatTypeFinder.java

fixed decoding

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerFlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/PassengerFlightServiceImp.java

This branch;
- closes #143 
- closes #144 
- closes #145

Updates and modifications cover the tasks from #143 to #146

---

FlightScheduler/src/main/java/com/su/FlightScheduler/APIs/MainSystemAPI/MainSystemController.java
FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserDataDTOFactory.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/resources/application.properties

Fixed a minor bug that caused passenger DTO to have 0 flights, it now holds the asked flight in flights list.

fixed minor bug in returning passenger list of a flight

---

FlightScheduler/src/main/java/com/su/FlightScheduler/DTO/FrontEndDTOs/UserFlightDataDTO.java
FlightScheduler/src/main/resources/application.properties

Now the booking id is shown in UserDataDTO.

Fixed another issue in passenger dto where booking id was unvisible

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java

fixed bug in updating flight

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/main/resources/application.properties
FlightScheduler/src/test/java/com/su/FlightScheduler/ControllerTest/FlightControllerTest.java
FlightScheduler/src/test/java/com/su/FlightScheduler/RepositoryTest/PassengerFlightRepositoryTests.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/FlightServiceTests.java

This branch does some modifications on Test Files.

Updates and modifications on Testing.

---

FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightService.java
FlightScheduler/src/main/java/com/su/FlightScheduler/Service/FlightServiceImp.java
FlightScheduler/src/test/java/com/su/FlightScheduler/ServiceTest/FlightServiceTests.java

Resolved the error that occured on the flighServiceImp.

Resolved an issue.
